"use client";

import { ArrowLeft, CheckCircle2, Clock3, Eye } from "lucide-react";
import { useEffect, useState } from "react";
import { useParams, useRouter } from "next/navigation";
import { AssessmentShell, ErrorPanel, LoadingPanel, PageHeading } from "@/components/assessment/assessment-shell";
import { Button } from "@/components/ui/button";
import { examService } from "@/lib/assessment-api";
import type { Exam, ExamAttempt } from "@/types/assessment";

export function SubmissionsPage() {
  const params = useParams<{ id: string }>(); const router = useRouter(); const [exam, setExam] = useState<Exam | null>(null); const [submissions, setSubmissions] = useState<ExamAttempt[]>([]); const [loading, setLoading] = useState(true); const [error, setError] = useState("");
  useEffect(() => { void Promise.all([examService.getExamById(params.id), examService.getSubmissions(params.id)]).then(([loadedExam, loadedSubmissions]) => { setExam(loadedExam); setSubmissions(loadedSubmissions); }).catch((cause) => setError(cause instanceof Error ? cause.message : "Không thể tải bài nộp")).finally(() => setLoading(false)); }, [params.id]);
  if (loading) return <AssessmentShell><LoadingPanel /></AssessmentShell>; if (error || !exam) return <AssessmentShell><ErrorPanel message={error || "Không tìm thấy bài kiểm tra"} /></AssessmentShell>;
  const submitted = submissions.filter((item) => item.status === "SUBMITTED");
  return <AssessmentShell><PageHeading eyebrow="Submission management" title="Danh sách bài nộp" description={`${exam.title} · ${exam.className}`} action={<Button variant="ghost" onClick={() => router.push(`/teacher/exams/${exam.id}`)}><ArrowLeft className="size-4" /> Chi tiết đề</Button>} /><div className="mb-5 grid gap-3 sm:grid-cols-3"><div className="rounded-2xl border border-slate-200 bg-white p-4"><p className="text-xs text-slate-400">Tổng bài nộp</p><p className="mt-1 text-2xl font-black">{submissions.length}</p></div><div className="rounded-2xl border border-slate-200 bg-white p-4"><p className="text-xs text-slate-400">Đã nộp</p><p className="mt-1 text-2xl font-black text-emerald-600">{submitted.length}</p></div><div className="rounded-2xl border border-slate-200 bg-white p-4"><p className="text-xs text-slate-400">Đang làm</p><p className="mt-1 text-2xl font-black text-amber-600">{submissions.filter((item) => item.status === "IN_PROGRESS").length}</p></div></div><div className="overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-card"><div className="hidden grid-cols-[minmax(0,1fr)_150px_180px_120px_100px] gap-4 border-b border-slate-100 bg-slate-50 px-5 py-3 text-[11px] font-black uppercase tracking-wide text-slate-400 md:grid"><span>Học sinh</span><span>Trạng thái</span><span>Thời gian nộp</span><span>Điểm</span><span /></div>{submissions.length === 0 ? <div className="p-12 text-center text-sm text-slate-500">Chưa có học sinh nộp bài.</div> : submissions.map((submission) => <article key={submission.id} className="grid gap-3 border-b border-slate-100 px-5 py-4 last:border-0 md:grid-cols-[minmax(0,1fr)_150px_180px_120px_100px] md:items-center md:gap-4"><div><p className="font-bold">{submission.studentName}</p><p className="mt-1 text-xs text-slate-400">{submission.examCode ? `Mã đề ${submission.examCode} · ` : ""}Mã bài làm: {submission.id.slice(0, 8)}</p></div><span className={`w-fit rounded-lg px-2.5 py-1 text-xs font-bold ${submission.status === "SUBMITTED" ? "bg-emerald-50 text-emerald-700" : "bg-amber-50 text-amber-700"}`}>{submission.status === "SUBMITTED" ? "Đã nộp" : "Đang làm"}</span><p className="text-sm text-slate-600">{submission.submittedAt ? new Date(submission.submittedAt).toLocaleString("vi-VN") : <span className="inline-flex items-center gap-1 text-slate-400"><Clock3 className="size-3" /> Chưa nộp</span>}</p><p className="font-black text-slate-800">{submission.score === null ? "—" : `${submission.score}/${exam.totalPoints}`}</p><Button size="sm" variant="outline" onClick={() => router.push(`/teacher/exams/${exam.id}/submissions/${submission.id}`)}><Eye className="size-4" /> Xem</Button></article>)}</div></AssessmentShell>;
}

export function SubmissionDetailPage() {
  const params = useParams<{ id: string; attemptId: string }>(); const router = useRouter(); const [data, setData] = useState<(ExamAttempt & { exam: Exam }) | null>(null); const [error, setError] = useState("");
  useEffect(() => { void fetchAttempt(params.attemptId).then(setData).catch((cause) => setError(cause instanceof Error ? cause.message : "Không thể tải bài làm")); }, [params.attemptId]);
  if (error) return <AssessmentShell><ErrorPanel message={error} /></AssessmentShell>; if (!data) return <AssessmentShell><LoadingPanel /></AssessmentShell>;
  return <AssessmentShell><PageHeading eyebrow="Submission review" title={`Bài làm của ${data.studentName}`} description={data.exam.title} action={<Button variant="ghost" onClick={() => router.push(`/teacher/exams/${params.id}/submissions`)}><ArrowLeft className="size-4" /> Danh sách bài nộp</Button>} /><div className="mb-5 rounded-2xl border border-slate-200 bg-white p-5 shadow-card"><div className="flex flex-wrap items-center gap-5 text-sm"><span className="inline-flex items-center gap-2 font-bold text-emerald-700"><CheckCircle2 className="size-4" />{data.status === "SUBMITTED" ? "Đã nộp" : "Đang làm"}</span>{data.examCode ? <span>Mã đề: <b>{data.examCode}</b></span> : null}<span>Điểm: <b>{data.score ?? "—"}/{data.exam.totalPoints}</b></span><span>Đúng: <b>{data.correctCount ?? "—"}/{data.exam.questions.length}</b></span></div></div><div className="space-y-3">{data.exam.questions.sort((a, b) => a.order - b.order).map((examQuestion, index) => { const answer = data.answers.find((item) => item.questionId === examQuestion.questionId); return <article key={examQuestion.questionId} className="rounded-2xl border border-slate-200 bg-white p-5 shadow-card"><div className="flex items-start justify-between gap-4"><div><p className="text-xs font-black uppercase tracking-wide text-brand-600">Câu {index + 1}</p><h2 className="mt-1 font-black">{examQuestion.question?.content ?? examQuestion.questionId}</h2></div><span className="rounded-lg bg-slate-100 px-2.5 py-1 text-xs font-bold">{examQuestion.points} điểm</span></div><div className="mt-4 rounded-xl bg-slate-50 p-4 text-sm"><p className="text-xs font-bold uppercase tracking-wide text-slate-400">Câu trả lời</p><p className="mt-2 font-semibold text-slate-700">{answer?.essayText || answer?.selectedOptionIds.join(", ") || "Bỏ trống"}</p></div></article>; })}</div></AssessmentShell>;
}

async function fetchAttempt(id: string): Promise<ExamAttempt & { exam: Exam }> {
  const { examAttemptService } = await import("@/lib/assessment-api");
  return examAttemptService.getAttempt(id);
}
